
###########################################################
# GENERATED FILE. DO NOT EDIT
# Generated by stackato-ops/dev-tools/gemlocker/gemlocker
###########################################################

source (ENV['RUBYGEMS_MIRROR'] or 'https://rubygems.org')

ruby '1.9.3' # prevents hard-to-diagnose errors with bundle install

gem 'activemodel'       ,   '3.2.17'
gem 'activerecord'      ,   '3.2.17'
gem 'activesupport'     ,   '3.2.17'
gem 'addressable'       ,    '2.3.5', :groups => [:test]
gem 'allowy'            ,    '0.4.0'
gem 'arel'              ,    '3.0.3'
gem 'axiom-types'       ,    '0.0.5'
gem 'backports'         ,    '3.3.5'
gem 'bcrypt-ruby'       ,    '3.1.2'
gem 'beefcake'          ,    '0.3.7'
gem 'builder'           ,    '3.0.4'
gem 'celluloid'         ,   '0.15.2', :groups => [:test]
gem 'cf-message-bus'    ,    '0.2.0', :github => "ActiveState/cf-message-bus"
gem 'cf-registrar'      ,    '1.0.1', :github => "cloudfoundry/cf-registrar"
gem 'cf-uaa-lib'        ,    '2.0.0', :github => "ActiveState/cf-uaa-lib", :ref => "3026895da933a7b1102735db96568c007b4c9148"
gem 'ci_reporter'       ,    '1.9.0'
gem 'clockwork'         ,    '0.7.0'
gem 'cloudfront-signer' ,    '2.1.1'
gem 'coderay'           ,    '1.1.0', :groups => [:development, :test]
gem 'coercible'         ,    '0.2.0'
gem 'colored'           ,      '1.2'
gem 'columnize'         ,    '0.3.6', :groups => [:development]
gem 'cookiejar'         ,    '0.3.0'
gem 'crack'             ,    '0.4.1', :groups => [:test]
gem 'daemons'           ,    '1.1.9'
gem 'debugger'          ,    '1.6.3', :groups => [:development]
gem 'debugger-linecache',    '1.2.0', :groups => [:development]
gem 'debugger-ruby_core_source',    '1.2.4', :groups => [:development]
gem 'delayed_job'       ,    '4.0.0'
gem 'delayed_job_active_record',    '4.0.0'
gem 'descendants_tracker',    '0.0.3'
gem 'diff-lcs'          ,    '1.2.5', :groups => [:default, :test]
gem 'docile'            ,    '1.1.1', :groups => [:test]
gem 'docopt'            ,    '0.5.0'
gem 'em-http-request'   ,    '1.1.1'
gem 'em-socksify'       ,    '0.3.0'
gem 'equalizer'         ,    '0.0.8'
gem 'errand'            ,    '0.7.3'
gem 'eventmachine'      ,    '1.0.3'
gem 'excon'             ,   '0.28.0'
gem 'fakefs'            ,    '0.4.3', :groups => [:test], :require => "fakefs/safe"
gem 'ffi'               ,    '1.9.3', :groups => [:test]
gem 'fluent-logger'     ,    '0.4.7'
gem 'fog'               ,   '1.18.0'
gem 'formatador'        ,    '0.2.4', :groups => [:default, :test]
gem 'futuroscope'       ,    '0.1.5'
gem 'grape'             ,    '0.7.1', :git => "https://github.com/intridea/grape.git"
gem 'guard'             ,    '2.2.4', :groups => [:test]
gem 'guard-rspec'       ,    '4.1.0', :groups => [:test]
gem 'hashie'            ,    '2.1.1'
gem 'http_parser.rb'    , '0.6.0.beta.2'
gem 'httpclient'        ,  '2.3.4.1'
gem 'i18n'              ,    '0.6.9'
gem 'ice_nine'          ,   '0.10.0'
gem 'ipaddress'         ,    '0.8.0'
gem 'json'              ,    '1.8.1'
gem 'json_pure'         ,    '1.8.1'
gem 'librrd'            ,    '1.0.3'
gem 'listen'            ,    '2.3.1', :groups => [:test]
gem 'loggregator_emitter',   '0.0.16'
gem 'loggregator_messages', '0.0.5.pre'
gem 'lumberjack'        ,    '1.0.4', :groups => [:test]
gem 'machinist'         ,    '1.0.6', :groups => [:test]
gem 'membrane'          ,    '1.0.0'
gem 'method_source'     ,    '0.8.2', :groups => [:development, :test]
gem 'mime-types'        ,      '2.0'
gem 'mini_portile'      ,    '0.5.2'
gem 'msgpack'           ,    '0.5.7'
gem 'multi_json'        ,    '1.8.2', :groups => [:default, :test]
gem 'multi_xml'         ,    '0.5.5'
gem 'multipart-post'    ,    '1.2.0'
gem 'mustache'          ,   '0.99.4'
gem 'mysql2'            ,   '0.3.14', :groups => [:db]
gem 'nats'              , '0.5.0.beta.12'
gem 'net-scp'           ,    '1.1.2'
gem 'net-ssh'           ,    '2.7.0'
gem 'nokogiri'          ,    '1.6.0'
gem 'parallel'          ,    '0.9.1', :groups => [:test]
gem 'parallel_tests'    ,   '0.16.5', :groups => [:test]
gem 'pg'                ,   '0.14.1', :groups => [:db, :default]
gem 'posix-spawn'       ,    '0.3.6'
gem 'pry'               , '0.9.12.4', :groups => [:development, :test]
gem 'rack'              ,    '1.5.2', :groups => [:default, :test]
gem 'rack-accept'       ,    '0.4.5'
gem 'rack-mount'        ,    '0.8.3'
gem 'rack-protection'   ,    '1.5.1'
gem 'rack-test'         ,    '0.6.2', :groups => [:test, :default]
gem 'rake'              ,   '10.1.0'
gem 'rb-fsevent'        ,    '0.9.3', :groups => [:test]
gem 'rb-inotify'        ,    '0.9.2', :groups => [:test]
gem 'rbvmomi'           ,    '1.6.0'
gem 'redis'             ,    '3.0.6'
gem 'rfc822'            ,    '0.1.4'
gem 'rspec'             ,   '2.14.1', :groups => [:default, :test]
gem 'rspec-core'        ,   '2.14.7', :groups => [:default, :test]
gem 'rspec-expectations',   '2.14.4', :groups => [:default, :test]
gem 'rspec-mocks'       ,   '2.14.4', :groups => [:default, :test]
gem 'rspec_api_documentation',    '2.0.0'
gem 'ruby-hmac'         ,    '0.4.0'
gem 'ruby-termios'      ,    '0.9.6'
gem 'rubyzip'           ,    '1.1.0'
gem 'safe_yaml'         ,    '0.9.7', :groups => [:test]
gem 'sequel'            ,   '3.48.0'
gem 'simplecov'         ,    '0.8.2', :groups => [:test]
gem 'simplecov-html'    ,    '0.8.0', :groups => [:test]
gem 'simplecov-rcov'    ,    '0.2.3', :groups => [:test]
gem 'sinatra'           ,    '1.4.4'
gem 'sinatra-contrib'   ,    '1.4.2'
gem 'slop'              ,    '3.4.7', :groups => [:development, :test]
gem 'sqlite3'           ,    '1.3.7', :groups => [:db, :default]
gem 'squash_ruby'       ,    '1.2.3'
gem 'stackato-kato'     ,    '3.0.0'
gem 'stager-client'     ,    '0.0.2', :github => "cloudfoundry/stager-client", :ref => "04c2aee9"
gem 'steno'             ,    '1.1.0'
gem 'steno-codec-text'  ,      '0.1', :path => "../steno-codec-text"
gem 'talentbox-delayed_job_sequel',    '4.0.0'
gem 'term-ansicolor'    ,    '1.0.7'
gem 'thin'              ,    '1.6.1'
gem 'thor'              ,   '0.18.1', :groups => [:test]
gem 'tilt'              ,    '1.4.1'
gem 'timecop'           ,    '0.7.0', :groups => [:test]
gem 'timers'            ,    '1.1.0', :groups => [:test]
gem 'trollop'           ,      '2.0'
gem 'tzinfo'            ,   '0.3.38'
gem 'unf'               ,    '0.1.3'
gem 'unf_ext'           ,    '0.0.6'
gem 'uuidtools'         ,    '2.1.4'
gem 'vcap-concurrency'  ,    '0.1.0', :github => "cloudfoundry/vcap-concurrency", :ref => "2a5b0179"
gem 'vcap_common'       ,    '3.0.0', :path => '../common'
gem 'virtus'            ,    '1.0.0'
gem 'vmstat'            ,    '2.0.0'
gem 'webmock'           ,   '1.16.0', :groups => [:test]
gem 'xmlparser'         ,  '0.7.2.1'
gem 'yajl-ruby'         ,    '1.1.0'

