
###########################################################
# GENERATED FILE. DO NOT EDIT
# Generated by stackato-ops/dev-tools/gemlocker/gemlocker
###########################################################

source (ENV['RUBYGEMS_MIRROR'] or 'https://rubygems.org')

ruby '1.9.3' # prevents hard-to-diagnose errors with bundle install

gem 'activesupport'     ,   '3.2.14'
gem 'addressable'       ,    '2.3.5', :groups => [:default, :test]
gem 'backports'         ,    '3.3.3'
gem 'bcrypt-ruby'       ,    '3.1.2'
gem 'beefcake'          ,    '0.3.7'
gem 'builder'           ,    '3.2.2'
gem 'cf-message-bus'    ,    '0.0.5', :git => "https://github.com/cloudfoundry/cf-message-bus.git"
gem 'cf-uaa-lib'        ,    '1.3.7', :git => "https://github.com/cloudfoundry/cf-uaa-lib.git", :ref => "8d34eede"
gem 'ci_reporter'       ,    '1.9.0'
gem 'cloudfront-signer' ,    '2.1.0'
gem 'coderay'           ,    '1.0.9', :groups => [:development, :test]
gem 'colored'           ,      '1.2'
gem 'columnize'         ,    '0.3.6', :groups => [:development]
gem 'cookiejar'         ,    '0.3.0'
gem 'crack'             ,    '0.4.1', :groups => [:test]
gem 'daemons'           ,    '1.1.9'
gem 'debugger'          ,    '1.6.1', :groups => [:development]
gem 'debugger-linecache',    '1.2.0', :groups => [:development]
gem 'debugger-ruby_core_source',    '1.2.3', :groups => [:development]
gem 'descendants_tracker',    '0.0.1'
gem 'diff-lcs'          ,    '1.2.4', :groups => [:default, :test]
gem 'docopt'            ,    '0.5.0'
gem 'em-hiredis'        ,    '0.2.1'
gem 'em-http-request'   ,    '1.0.3'
gem 'em-socksify'       ,    '0.3.0'
gem 'eventmachine'      ,    '1.0.1'
gem 'eventmachine-tail' ,    '0.6.4'
gem 'excon'             ,   '0.25.3'
gem 'ffi'               ,    '1.9.0', :groups => [:test]
gem 'fluent-logger'     ,    '0.4.6'
gem 'fog'               ,   '1.15.0'
gem 'formatador'        ,    '0.2.4', :groups => [:default, :test]
gem 'fraggle'           ,    '4.0.1'
gem 'fraggle-block'     ,    '0.2.0'
gem 'grape'             ,    '0.5.0'
gem 'guard'             ,    '1.8.2', :groups => [:test]
gem 'guard-rspec'       ,    '3.0.2', :groups => [:test]
gem 'hashie'            ,    '2.0.5'
gem 'hiredis'           ,    '0.4.5'
gem 'http_parser.rb'    ,    '0.5.3'
gem 'httpclient'        ,  '2.3.4.1'
gem 'i18n'              ,    '0.6.5'
gem 'ipaddress'         ,    '0.8.0'
gem 'json'              ,    '1.8.0'
gem 'json_pure'         ,    '1.8.0'
gem 'listen'            ,    '1.3.0', :groups => [:test]
gem 'lumberjack'        ,    '1.0.4', :groups => [:test]
gem 'machinist'         ,    '1.0.6', :groups => [:test]
gem 'membrane'          ,    '0.0.2'
gem 'method_source'     ,    '0.8.2', :groups => [:development, :test]
gem 'mime-types'        ,     '1.24'
gem 'mini_portile'      ,    '0.5.1'
gem 'msgpack'           ,    '0.5.5'
gem 'multi_json'        ,    '1.7.9', :groups => [:default, :test]
gem 'multi_xml'         ,    '0.5.5'
gem 'multipart-post'    ,    '1.2.0'
gem 'mustache'          ,   '0.99.4'
gem 'mysql2'            ,   '0.3.13', :groups => [:db]
gem 'nats'              ,   '0.4.26'
gem 'net-scp'           ,    '1.1.2'
gem 'net-ssh'           ,    '2.6.8'
gem 'nokogiri'          ,    '1.6.0'
gem 'parallel'          ,    '0.7.1', :groups => [:test]
gem 'parallel_tests'    ,   '0.15.3', :groups => [:test]
gem 'pg'                ,   '0.14.1', :groups => [:db, :default]
gem 'posix-spawn'       ,    '0.3.6'
gem 'pry'               , '0.9.12.2', :groups => [:development, :test]
gem 'rack'              ,    '1.5.2', :groups => [:default, :test]
gem 'rack-accept'       ,    '0.4.5'
gem 'rack-mount'        ,    '0.8.3'
gem 'rack-protection'   ,    '1.5.0'
gem 'rack-test'         ,    '0.6.2', :groups => [:test, :default]
gem 'rake'              ,   '10.1.0'
gem 'rb-fsevent'        ,    '0.9.3', :groups => [:test]
gem 'rb-inotify'        ,    '0.9.1', :groups => [:test]
gem 'rb-kqueue'         ,    '0.2.0', :groups => [:test]
gem 'redis'             ,    '3.0.4'
gem 'rfc822'            ,    '0.1.4'
gem 'rspec'             ,   '2.14.1', :groups => [:default, :test]
gem 'rspec-core'        ,   '2.14.5', :groups => [:default, :test]
gem 'rspec-expectations',   '2.14.2', :groups => [:default, :test]
gem 'rspec-mocks'       ,   '2.14.3', :groups => [:default, :test]
gem 'ruby-graphviz'     ,    '1.0.9', :groups => [:development]
gem 'ruby-hmac'         ,    '0.4.0'
gem 'ruby-termios'      ,    '0.9.6'
gem 'safe_yaml'         ,    '0.9.5', :groups => [:test]
gem 'sequel'            ,    '4.1.1'
gem 'simplecov'         ,    '0.7.1', :groups => [:test]
gem 'simplecov-html'    ,    '0.7.1', :groups => [:test]
gem 'simplecov-rcov'    ,    '0.2.3', :groups => [:test]
gem 'sinatra'           ,    '1.4.3'
gem 'sinatra-contrib'   ,    '1.4.1'
gem 'slop'              ,    '3.4.6', :groups => [:development, :test]
gem 'sqlite3'           ,    '1.3.7', :groups => [:db, :default]
gem 'squash_ruby'       ,    '1.2.0'
gem 'stackato-kato'     ,   '2.11.0'
gem 'stager-client'     ,    '0.0.2', :git => "https://github.com/cloudfoundry/stager-client.git", :ref => "04c2aee9"
gem 'steno'             ,    '1.1.0'
gem 'term-ansicolor'    ,    '1.0.7'
gem 'thin'              ,    '1.5.1'
gem 'thor'              ,   '0.18.1', :groups => [:test]
gem 'tilt'              ,    '1.4.1'
gem 'timecop'           ,    '0.6.3', :groups => [:test]
gem 'vcap-concurrency'  ,    '0.1.0', :git => "https://github.com/cloudfoundry/vcap-concurrency.git", :ref => "2a5b0179"
gem 'vcap_common'       ,    '2.2.1', :git => "https://github.com/cloudfoundry/vcap-common.git"
gem 'vic'               ,    '1.0.0'
gem 'virtus'            ,    '0.5.5'
gem 'vmstat'            ,    '2.0.0'
gem 'webmock'           ,   '1.13.0', :groups => [:test]
gem 'xmlparser'         ,  '0.7.2.1'
gem 'yajl-ruby'         ,    '1.1.0'

