
# Names of components to filter out from reading and writing via the config api.
component_blacklist:
  - app_store

# Names of config keys which will have their values filtered out from reading and writing via the config api.
key_blacklist:
  - password
  - shared_secret
  - symmetric_secret
  - auth_password
  - db_encryption_key
  - client_secret
  - stackato_ssh_keypair_alluser
  - stackato_ssh_keypair_frontend
  - signing_key
  - verification_key
  - secret