---
processes:

  cloud_controller_ng:
    logging: RW
    info:
      name: R
      build: R
      support_address: RW
      description: R
      api_version: R
    app_uris: RW
    allowed_repos: RW
    maintenance_mode: RW
    max_user_drains: R
    quota_definitions: RW
    staging:
      max_staging_runtime: RW

  health_manager:
    logging: RW

  router2g:
    logging: RW

  dea_ng:
    logging: RW
    resources:
      memory_max_percent: RW
    staging:
      max_staging_duration: RW
      memory_limit_mb: R
      disk_limit_mb: R

  harbor_gateway:
    plan_management:
      plans:
        free:
          allow_over_provisioning: RW

  harbor_node:
    logging: RW
    host_external: RW
    hostname_external: RW
    port_range: RW

  mysql_gateway:
    logging: RW
    plan_management:
      plans:
        free:
          allow_over_provisioning: RW

  mysql_node:
    logging: RW
    capacity: RW
    max_db_size: RW

  postgresql_gateway:
    logging: RW
    plan_management:
      plans:
        free:
          allow_over_provisioning: RW

  postgresql_node:
    logging: RW
    capacity: RW
    max_db_size: RW

  rabbit_gateway:
    logging: RW
    plan_management:
      plans:
        free:
          allow_over_provisioning: RW

  rabbit_node:
    logging: RW
    capacity: RW
    max_memory: RW

  rabbit3_gateway:
    logging: RW
    plan_management:
      plans:
        free:
          allow_over_provisioning: RW

  rabbit3_node:
    logging: RW
    capacity: RW
    max_memory: RW

  redis_gateway:
    logging: RW
    plan_management:
      plans:
        free:
          allow_over_provisioning: RW

  redis_node:
    logging: RW
    capacity: RW
    max_memory: RW

  mongodb_gateway:
    logging: RW
    plan_management:
      plans:
        free:
          allow_over_provisioning: RW

  mongodb_node:
    logging: RW
    capacity: RW

  filesystem_gateway:
    logging: RW
    plan_management:
      plans:
        free:
          allow_over_provisioning: RW

  filesystem_node:
    logging: RW
    capacity: RW
    max_fs_size: RW

  memcached_node:
    logging: RW
    capacity: RW
    memcached_memory: RW

  memcached_gateway:
    logging: RW
    plan_management:
      plans:
        free:
          allow_over_provisioning: RW

  logyard:
    retrylimits: R
    drains: R

  systail:
    max_record_size: RW

  apptail:
    max_record_size: RW

